### PR TITLE
Add French (🇫🇷) translation

### PR DESCRIPTION
**Pull request by Elliot67**
FYI : Running the lint command change a lot of sources files, I decided not to commit them.

### CODE REVIEW

**Review by iorate — CHANGES_REQUESTED** [review]
The screenshots are in English (copies of en/\*.png).
Please remove them or replace them with French ones.

**Comment by Elliot67** [comment]
@iorate The images have been removed.

**Review by iorate — APPROVED** [review]

**Comment by iorate** [comment]
Great,

**Comment by iorate** [comment]
@Elliot67 I'm sorry, I misunderstood. I thought that missing screenshots would automatically fall back to the default language (English).
I will add English screenshots to the French (and Ukrainian) pages.

**Pull request merged**
