### PR TITLE
Add Rightwing Media, Conspiracy Media, Fake-News Media blacklists

### PR DESCRIPTION
**Pull request by RubenKelevra**
This PR creates a dedicated media section and adds the following blacklist:

- Rightwing Media
- Fake-News Media
- Conspiracy Media

### CODE REVIEW

**Comment by aug-dev** [comment]
Hey there!

First off, thanks for you contribution.

Without even checking the specific websites you included in your list, I don't think it is quite a good idea for such lists to be included in the official website:



> * Rightwing Media
> 
> * Fake-News Media
> 
> * Conspiracy Media

All the three categories here have, by definition, strong political views.

It would be hard for the subscription page to remain neutral if we begin to include websites to a "Fake-News" category.

Would we be required to do fact-checking? Probably not, we're just an open-source project, but the end-user looking at the page would probably **imply** that at least some research was done.

Besides, I'm 100% certain that this is basically an invitation for futures GitHub issues with the following requests:

**Remove my favorite website from the Conspiracy Media! ONLY THEY KNOW THE TRUTH!**

It could give off the impression that uBlacklist as a project condones such opinions, when that might not be the case.

I don't know. What do you think about this?

---

By the way, you are still allowed to share these subscription lists on your own, I just don't think it is a good idea to include them on the official website.

**Comment by RubenKelevra** [comment]
Hey thanks for taking the time to write such a long reply to this.

I don't see an issue with listing user-created lists on the official website as it's clearly marked as created by me.

Apart from that, it's not a matter of opinion, neither by me nor by you or this project, as each entry has a source attached where people with complains can read the review and why it was added.

It's also not a matter of condones options, but a way to optimize the search results for individual likings.

I think as a project the best approach is to be open about such lists and let the users decide which they want to use and which one not - like before.

Hope this helps in your decision!

**Comment by RubenKelevra** [comment]
Okay. I don't really get where the difference is between precious community created blacklists and mine - both are not under the control of the project and both are listed here.

How about we make a disclaimer on the top of the page to point this out for clearly to the users, that this is user driven content, not related, endorsed or controlled by the project and listed here in a neutral fashion?

I mean I think of this more like a technical listing, like DNS, than part of the program.

**Comment by RubenKelevra** [comment]
I've added the disclaimer to this PR

**Comment by aug-dev** [comment]
> how about adding a disclaimer at the top of the page?

I was going to suggest exactly that.

Thanks for writing the disclaimer, I think it is (at a first glance) really well-written.

I still think we are going to get some weird PRs in the future due to this, but the warning solves a lot of the problems.

We probably should probably provide it with some styling, but this could be done in a different PR.

I think it is good to go.

**Comment by RubenKelevra** [comment]
> we are going to get some weird PRs in the future due to this

Hope the PRs are more aimed at my repos. I mean, PRs here can just remove the whole list, which I have to say defeats the purpose. If someone doesn't like a list, just don't use it. :)

> I think it is good to go.

Cool!

**Review by iorate — APPROVED** [review]
Pretty much OK

**Pull request merged**
