### PR TITLE
fix(safari): fix problems with Google Search on iOS

### PR DESCRIPTION
**Pull request by iorate**
Fix the following problems:
- (web) does not work
- (images) controls and actions are slightly out of alignment
- (videos) wrong URLs are used for filtering
- (news) does not work

@HoneyLuka Would you please try this?

### CODE REVIEW

**Comment by HoneyLuka** [comment]
Okay, I'll test it and let you know the results later

**Comment by HoneyLuka** [comment]
- [x] (web) does not work
- [x] (images) controls and actions are slightly out of alignment
- [x] (news) does not work
- [ ] (videos) wrong URLs are used for filtering

I don't know what to test for in the video section, I compared 7.8.1 with this version and both seem to work fine.

**Comment by iorate** [comment]
Sorry for my lack of explanation.
The current version tries to block www.google.com for some results (results with "expand" buttons).

videos

**Comment by HoneyLuka** [comment]
Of course, I will immediately release an update on the app store. 7.8.3 or 7.9.0 I will follow your release version.

**Comment by iorate** [comment]
OK, I will merge #249 and release #249 and #250 (this) as **7.8.3** right now.

**Pull request merged**
