### PR TITLE
Update subscriptions.md

### PR DESCRIPTION
**Pull request by legendary-creeper**
Added [Safebrowsing for Minecrafters  🛡️⛏️](https://codeberg.org/legendary_creeper/safebrowsing-for-minecrafters) to the subscriptions page, I've added it to the "Others" section since I though it would fit their the most.

### CODE REVIEW

**Comment by RubenKelevra** [comment]
I don't think it fits the "Others" category - which contains a list of blocklists and a personal blacklist. I think it would be better to create a new category for this.

Btw: Nice work!

**Comment by RubenKelevra** [comment]
How about just "Games" or "Gaming"?

**Comment by aug-dev** [comment]
> How about just "Games" or "Gaming"?

I think this is a good idea.

It's general enough and likely to be expanded later with new blacklists.

**Comment by iorate** [comment]
@legendary-creeper If you agree that it is appropriate to place your subscription under the "Games" or "Gaming" category (or another new category), please update your pull request accordingly.

**Review by iorate — APPROVED** [review]

**Pull request merged**
