### PR TITLE
Screenshots for webstore

### PR DESCRIPTION
**Pull request by uDEV2019**
to show german user interface

### CODE REVIEW

**Comment by iorate** [comment]
Screenshots should be 1280x800 (preferred) or 640x400.
https://developer.chrome.com/docs/webstore/images/#screenshots

**Comment by iorate** [comment]
Sorry that I didn't explain it clearly. I updated README.

**Comment by uDEV2019** [comment]
Sorry, my mistake because i didn't informed me before i was creating the screenshots.

It is fixed now, to 1280x800.

**Comment by iorate** [comment]
`chrome-screenshot-2.png` has a size of 1280x810

**Comment by uDEV2019** [comment]
Now, everything should be ok.

**Pull request merged**
