### PR TITLE
searx: add search.whatever.social

### PR DESCRIPTION
**Pull request by p00f**
https://whatever.social:
> Whatever Social is a collection of FOSS alternative frontends and self-hosted services to try and close the gap between viewing mainstream social media and privacy

They recently added a searx instance, ~https://searx.whatever.social~ https://search.whatever.social

### CODE REVIEW

**Comment by iorate** [comment]
I cannot confirm that https://searx.whatever.social/ works. The browser reports a SSL error and the same content as https://whatever.social/ is returned.

**Comment by p00f** [comment]
sorry, I meant search.whatever.social. The pattern in the PR is correct though

**Comment by p00f** [comment]
@iorate bump

**Comment by iorate** [comment]
The SERP URL is `https://search.whatever.social/searxng/search` and does not match `'*://search.whatever.social/search*'`.

**Comment by p00f** [comment]
fixed

**Review by iorate — APPROVED** [review]

**Pull request merged**
