### PR TITLE
fix(brave): blocking search results no longer work

### PR DESCRIPTION
**Pull request by rsuwa**
## Issue

<https://github.com/iorate/ublacklist/issues/371>

## Changes from the previous version

- Slight modifications were made to the target DOM in accordance with Brave Search's specification changes.
- Minor style modifications
- Add missing support for Brave Goggle Search

*Note: Subdomains are not supported in Brave Image Search due to the difficulty in obtaining the complete URL of the image link. (e.g., if the link is to "www.example.com", it will block the entire "example.com"). I have not been able to do anything about this, but if you think you can improve the logic, please advise.

https://github.com/iorate/ublacklist/blob/408192680c5efa034d7521b41b4a2e11624b4f27/src/scripts/search-engines/brave.ts#L54-L61

### CODE REVIEW

**Comment by rsuwa** [comment]
@iorate
The detailed cause is under investigation, but it appears that the DOM is being modified after the load event is fired in Brave Search's specification.
Reference: https://i.gyazo.com/6e346a37725c089399e291c8f80aea1c.gif

I have tried to solve the problem by changing `run_at` in `manifest.json.ts` to `document_idle`, using `MutationObserver`, etc., but my implementation skills were not enough to solve the problem, so I would like to borrow some of your knowledge.

I apologize for the very naive implementation, but changing `content-script.tsx` as follows will solve the problem once, but it is not a clean way and I would like to avoid it.

```tsx
// main();
setTimeout(() => {
  main();
}, 1000);
```

**Comment by rsuwa** [comment]
> @iorate The detailed cause is under investigation, but it appears that the DOM is being modified after the load event is fired in Brave Search's specification.
> 
> Reference:  [ 68747470733a2f2f692e6779617a6f2e636f6d2f36653334366133373732356330383933393965323931633866383061656131632e676966 ](https://camo.githubusercontent.com/327f29efd5789c9f1125db4e84c8f0ed72c8f6c98cd1c54fa50d53daec845582/68747470733a2f2f692e6779617a6f2e636f6d2f36653334366133373732356330383933393965323931633866383061656131632e676966) [ ](https://camo.githubusercontent.com/327f29efd5789c9f1125db4e84c8f0ed72c8f6c98cd1c54fa50d53daec845582/68747470733a2f2f692e6779617a6f2e636f6d2f36653334366133373732356330383933393965323931633866383061656131632e676966)
> 
> I have tried to solve the problem by changing `run_at` in `manifest.json.ts` to `document_idle`, using `MutationObserver`, etc., but my implementation skills were not enough to solve the problem, so I would like to borrow some of your knowledge.
> 
> I apologize for the very naive implementation, but changing `content-script.tsx` as follows will solve the problem once, but it is not a clean way and I would like to avoid it.
> 
> ```tsx
> // main();
> setTimeout(() => {
>   main();
> }, 1000);
> ```

PS: This problem did not occur in Firefox, so it may be specific to Chrome or Chromium-based browsers.

Environment
- OS: macOS Sonoma 14.1.1
- Browser (Firefox): Firefox 119.0.1
- Browser (Chrome): Chrome 119.0.6045.15
Browser is newly launched from launch.json, without any other extensions, and is in a vanilla state.

**Comment by iorate** [comment]
@rsuwa
Thank you for your contribution.
I think the only way we can do now is to delay the content script.
I have modified the main code to support delaying.

**Comment by iorate** [comment]
> *Note: Subdomains are not supported in Brave Image Search due to the difficulty in obtaining the complete URL of the image link. (e.g., if the link is to "www.example.com", it will block the entire "example.com"). I have not been able to do anything about this, but if you think you can improve the logic, please advise.

I think your solution is the best we can do.

**Comment by rsuwa** [comment]
> @rsuwa Thank you for your contribution. I think the only way we can do now is to delay the content script. I have modified the main code to support delaying.

Thanks for your modification!
After several attempts, I thought 100 ms would be enough.

**Pull request merged**
