### PR TITLE
add cn.bing.com support

### PR DESCRIPTION
**Pull request by Awezome**

### CODE REVIEW

**Comment by iorate** [comment]
@Awezome 
1. Did you confirm that this extension actually works on `cn.bing.com`? I cannot access it because it is redirected to `www.bing.com` in my environment (in Japan).
2. How about other search scopes (images, videos, ...)? This extension supports images, videos and news search offered by `www.bing.com`, but I have no clue about `cn.bing.com`.

**Comment by Awezome** [comment]
> @Awezome
> 
> 1. Did you confirm that this extension actually works on `cn.bing.com`? I cannot access it because it is redirected to `www.bing.com` in my environment (in Japan).
> 2. How about other search scopes (images, videos, ...)? This extension supports images, videos and news search offered by `www.bing.com`, but I have no clue about `cn.bing.com`.

1. Yes. It is redirected to cn.bing.com when access www.bing.com in China.
2. I don't need images, videos page so just added web search page url.

**Comment by iorate** [comment]
@Awezome 
Sorry for tha late reply.
1. All right, thanks.
2. Does it work when you add the image/video/news search URLs? If so, I think, they should be added.

**Comment by Awezome** [comment]
> 2\. add the image/video/news search URLs

Okay . Added image/video/news search urls .

**Comment by iorate** [comment]
@Awezome thanks. merged.

**Pull request merged**
